use_frameworks!

platform :ios, '9.0'

target 'SugerKit_Example' do
  pod 'SugerKit', :path => '../'

  target 'SugerKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
