platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!
#source 'https://github.com/CocoaPods/Specs.git'

target 'SugerKit_Example' do
  pod 'SugerKit', :path => '../'

  target 'SugerKit_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
